project:
  type: book
  output-dir: docs

book:
  title: "Jonathan Wiguna"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "Jonathan Wiguna"
  date: "10/18/2025"
  chapters:
    - index.qmd
    - part: "Ujian Tengah Semester"
      chapters:
        - text: "UTS-1 All About Me"
          file: All_About_me/index.qmd
        - text: "UTS-2 My Songs for You"
          file: My_Song_for_You/index.qmd
        - text: "UTS-3 My Stories for You"
          file: My_Stories_for_You/index.qmd
        - text: "UTS-4 My SHAPE"
          file: My_Shapes/index.qmd
        - text: "UTS-5 My Personal Reviews"
          file: My_Personal_Reviews/index.qmd
    - part: "Ujian Akhir Semester"
      chapters:
        - text: "UAS-1 My Concepts"
          file: My_Concepts/index.qmd
        - text: "UAS-2 My Opinions"
          file: My_Opinions/index.qmd
        - text: "UAS-3 My Innovations"
          file: My_Innovations/index.qmd
        - text: "UAS-4 My Knowledge"
          file: My_Knowledge/index.qmd
        - text: "UAS-5 My Professional Reviews"
          file: My_Professional_Reviews/index.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
  pdf:
    documentclass: scrreprt
